# This file was generated by GoReleaser. DO NOT EDIT.
class Servicebuilder < Formula
  desc "A gRPC based Micro Service scaffolding in GoLang with HTTP/JSON gRPC gateway"
  homepage "https://cnative.dev"
  url "https://github.com/cnative/servicebuilder/releases/download/v0.9.4/servicebuilder_darwin_amd64.tar.gz"
  version "0.9.4"
  sha256 "aae1b38c0e5c2d8408818c99fddfaf9d2ff42cee83f482db35f1c413b126786a"

  def install
    bin.install "servicebuilder"
  end

  test do
    system "#{bin}/servicebuilder version"
  end
end
