# This file was generated by GoReleaser. DO NOT EDIT.
class Servicebuilder < Formula
  desc "A gRPC based Micro Service scaffolding in GoLang with HTTP/JSON gRPC gateway"
  homepage "https://cnative.dev"
  url "https://github.com/cnative/servicebuilder/releases/download/v0.9.8/servicebuilder_darwin_amd64.tar.gz"
  version "0.9.8"
  sha256 "fa69eb952b81056138370e1d8aabdd1ab492ab60e0aa75af4d094aa420c2e857"

  def install
    bin.install "servicebuilder"
  end

  test do
    system "#{bin}/servicebuilder version"
  end
end
